export { default as HomePage } from './HomePage'
export { default as CatalogPage } from './CatalogPage'
export { default as ProductPage } from './ProductPage'
export { default as CartPage } from './CartPage'
export { default as CheckoutPage } from './CheckoutPage'
export { default as ProfilePage } from './ProfilePage'